apiVersion: config.openshift.io/v1
kind: Project
metadata:
  name: cluster
spec:
  projectRequestMessage: Contact your instructor to provision the project
  projectRequestTemplate:
    name: rhd-workshop-project-request
