apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-openshift-oauth
spec:
  dex:
    image: quay.io/redhat-cop/dex
    version: v2.22.0-openshift
    openShiftOAuth: true
  rbac:
    defaultPolicy: "role:readonly"
    policy: |
      g, system:cluster-admins, role:admin
    scopes: "[groups]"
  server:
    route:
      enabled: true
  # tls:
  #   ca:
  #     secretName: my-dev-ca
