roles:
 - name: kameshsampath.openshift_app_spices
   src: https://github.com/kameshsampath/ansible-role-openshift-spices
   version: master

collections:
  - name: community.kubernetes
    version: 0.11.1