---
- name: Create Eclipse Che Namespace
  community.kubernetes.k8s:
    state: present
    kind: Namespace
    name: che

- name: "Install Operator Group::Eclipse Che"
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template','che/subscription.yaml.j2') | from_yaml  }}"
    wait: yes

- name: "Install Operator::Eclipse Che"
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template','che/subscription.yaml.j2') | from_yaml  }}"
    wait: yes

- name: "Wait for Operator::Eclipse Che"
  include_tasks: utils/wait_for_operator_and_sub.yml
  vars:
    subscription_name: eclipse-che

- name: Create Eclipse Che Workspace
  community.kubernetes.k8s:
    state: present
    definition: "{{ item | from_yaml }}"
    wait: yes
    wait_timeout: 180
    wait_sleep: 10
    wait_condition:
      type: Ready
  with_file: "{{ eclipse_che_cr }}"
  no_log: True
  register: eclipse_che_status
