---

- name: Create ACM namespace
  community.kubernetes.k8s:
    state: present
    kind: Namespace
    name: "{{ acm_namespace }}"

- name: Create ACM::Operator Group
  community.kubernetes.k8s:
    state: present
    namespace: "{{ acm_namespace }}"
    definition: "{{ lookup('template','acm/operator-group.yaml.j2') | from_yaml  }}"
    wait: yes

- name: Install Operator::ACM
  community.kubernetes.k8s:
    state: present
    namespace: "{{ acm_namespace }}"
    definition: "{{ lookup('template','acm/subscription.yaml.j2') | from_yaml  }}"
    wait: yes

- name: Wait for ACM Operator to be ready
  include_tasks: utils/wait_for_operator_and_sub.yml
  vars:
    subscription_name: advanced-cluster-management
    sub_namespace: "{{ acm_namespace }}"

- name: Deploy Multi Cluster Hub
  community.kubernetes.k8s:
    state: present
    namespace: "{{ acm_namespace }}"
    definition: "{{ item | from_yaml }}"
    wait: no
  with_file:
   - "{{ acm_cr }}"

- name: Get Multi Cluster Hub Name
  set_fact:
    acm_cr: "{{ item | from_yaml }}"
  no_log: yes
  with_file:
  -  "{{ acm_cr }}"

- name: Waiting for Multi Cluster Hub to be running
  community.kubernetes.k8s_info:
    api_version: operator.open-cluster-management.io/v1
    kind: MultiClusterHub
    namespace: "{{ acm_namespace }}"
    name: "{{ acm_cr.metadata.name }}"
  register: acm_status
  retries: 60
  delay: 10
  until: acm_status.resources and acm_status.resources[0].status is defined and acm_status.resources[0].status.phase == 'Running'